package resetor

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestReset(t *testing.T) {
	tests := []struct {
		name    string
		src     any
		want    string
		wantErr bool
	}{
		{
			name:    "no file",
			src:     `package empty`,
			want:    "",
			wantErr: false,
		},
		{
			name: "no comment structs",
			src: `package nopackage
type Basic struct {
	Name string
}`,
			want:    "",
			wantErr: false,
		},
		{
			name: "one struct with basic field",
			src: `package basic

// generate:reset
type Basic struct {
	Name string
}`,
			want: `package basic

// Code generated by reset tool. DO NOT EDIT.

func (b *Basic) Reset() {
	if b == nil {
		return
	}

	// resets Name
	b.Name = ""
}
`,
			wantErr: false,
		},
		{
			name: "one struct with slice field",
			src: `package slice
// generate:reset
type Slice struct {
	Items []string
}`,
			want: `package slice

// Code generated by reset tool. DO NOT EDIT.

func (s *Slice) Reset() {
	if s == nil {
		return
	}

	// resets Items
	if s.Items != nil {
		s.Items = s.Items[:0]
	}
}
`,
			wantErr: false,
		},
		{
			name: "one struct with map field",
			src: `package mapstruct
// generate:reset
type Map struct {
	Data map[string]int
}`,
			want: `package mapstruct

// Code generated by reset tool. DO NOT EDIT.

func (m *Map) Reset() {
	if m == nil {
		return
	}

	// resets Data
	if m.Data != nil {
		clear(m.Data)
	}
}
`,
			wantErr: false,
		},
		{
			name: "one struct with pointer field",
			src: `package pointer
// generate:reset
type Pointer struct {
	Value *int
}`,
			want: `package pointer

// Code generated by reset tool. DO NOT EDIT.

func (p *Pointer) Reset() {
	if p == nil {
		return
	}

	// resets Value
	if p.Value != nil {
		*p.Value = 0
	}
}
`,
			wantErr: false,
		},
		{
			name: "one struct with array field",
			src: `package array
// generate:reset
type Array struct {
	Vector [10]int
}`,
			want: `package array

// Code generated by reset tool. DO NOT EDIT.

func (a *Array) Reset() {
	if a == nil {
		return
	}

	// resets Vector
	for i := 0; i < len(a.Vector); i++ {
		a.Vector[i] = 0
	}
}
`,
			wantErr: false,
		},
		{
			name: "one struct with array pointer field",
			src: `package array
// generate:reset
type Array struct {
	Vector [10]*int
}`,
			want: `package array

// Code generated by reset tool. DO NOT EDIT.

func (a *Array) Reset() {
	if a == nil {
		return
	}

	// resets Vector
	for i := 0; i < len(a.Vector); i++ {
		*a.Vector[i] = 0
	}
}
`,
			wantErr: false,
		},
		{
			name: "invalid Go code",
			src: `package invalid
invalid syntax here`,
			want:    "",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			err := Reset("", tt.src, &buf)

			if tt.wantErr {
				require.Error(t, err)
				return
			}

			assert.Equal(t, tt.want, buf.String())
		})
	}
}
