package writer

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	genComment = "// Code generated by reset tool. DO NOT EDIT."
	foo        = `func (f *Foo) Reset() {
	Value = ""
}`
	bar = `func (b *Bar) Reset() {
	Value = ""
}`
)

func TestWriteResetFile(t *testing.T) {
	tests := []struct {
		name           string
		packageName    string
		resetFunctions []string
		want           string
		wantErr        error
	}{
		{
			name:           "empty package name",
			packageName:    "",
			resetFunctions: []string{foo},
			want:           "",
		},
		{
			name:           "no functions",
			packageName:    "nofunctions",
			resetFunctions: []string{},
			want:           fmt.Sprintf("package nofunctions\n\n%s\n", genComment),
		},
		{
			name:           "single function",
			packageName:    "single",
			resetFunctions: []string{foo},
			want:           fmt.Sprintf("package single\n\n%s\n\n%s\n", genComment, foo),
		},
		{
			name:           "multiple functions",
			packageName:    "multiple",
			resetFunctions: []string{foo, bar},
			want:           fmt.Sprintf("package multiple\n\n%s\n\n%s\n\n%s\n", genComment, foo, bar),
		},
		{
			name:           "format error",
			packageName:    "formaterror",
			resetFunctions: []string{"invalid go code {}"},
			want:           "",
			wantErr:        errFormat,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer

			err := WriteResetFile(tt.packageName, tt.resetFunctions, &buf)

			if tt.wantErr != nil {
				require.ErrorIs(t, err, tt.wantErr)
				return
			}
			assert.Equal(t, buf.String(), tt.want)
		})
	}
}
