package writer

import (
	"errors"
	"fmt"
	"go/format"
	"io"
	"strings"

	"github.com/MaksimMakarenko1001/ya-go-advanced/cmd/reset/model"
)

const resetFile = "package %s\n// Code generated by reset tool. DO NOT EDIT.\n\n%s\n"

var errFormat = errors.New("format error")

// WriteResetFile writes the generated reset functions to a specified writer
func WriteResetFile(name model.PackageName, resets []model.ResetFunc, writer io.Writer) error {
	if name == "" {
		return nil
	}

	content := fmt.Sprintf(resetFile, name, strings.Join(resets, "\n\n"))

	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("%w: %w", errFormat, err)
	}

	if _, err := writer.Write(formatted); err != nil {
		return fmt.Errorf("write error: %w", err)
	}

	return nil
}
